Document: amxa-safesearch
Title: Debian amxa-safesearch Manual
Author: <insert document author here>
Abstract: This manual describes what amxa-safesearch is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/amxa-safesearch/amxa-safesearch.sgml.gz

Format: postscript
Files: /usr/share/doc/amxa-safesearch/amxa-safesearch.ps.gz

Format: text
Files: /usr/share/doc/amxa-safesearch/amxa-safesearch.text.gz

Format: HTML
Index: /usr/share/doc/amxa-safesearch/html/index.html
Files: /usr/share/doc/amxa-safesearch/html/*.html
